use_frameworks!

platform :ios, '10.0'

target 'TestPodKit_Example' do
  pod 'TestPodKit', :path => '../'

  target 'TestPodKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
